env:
  global:
    - BINSTAR_USER: menpo
  matrix:
  - PYTHON_VERSION=2
  - PYTHON_VERSION=3

install:
- wget https://raw.githubusercontent.com/jabooth/condaci/master/condaci.py -O condaci.py
- python condaci.py setup $PYTHON_VERSION --channel $BINSTAR_USER
- export PATH=/home/travis/miniconda/bin:$PATH

script:
- python condaci.py auto ./conda --binstaruser $BINSTAR_USER --binstarchannel main --binstarkey $BINSTAR_KEY
