build: false

environment:
  global:
    BINSTAR_USER: menpo
    BINSTAR_KEY: temp
#    CMD_IN_ENV: "cmd /E:ON /V:ON /C C:\\run_with_env.cmd"
#    PYTHON_ARCH: 64
  matrix:
    - PYTHON_VERSION: 2
    - PYTHON_VERSION: 3

platform:
- x64

init:
- ps: Start-FileDownload 'https://raw.githubusercontent.com/jabooth/traviconda/master/traviconda.py' C:\\traviconda.py; echo "Done"
- python C:\\traviconda.py setup %PYTHON_VERSION% --channel %BINSTAR_USER%

install:
#- cmd /E:ON /V:ON /C "C:\\run_with_env.cmd C:\\Miniconda\\Scripts\\conda build conda"
- C:\\Miniconda\\python C:\\traviconda.py auto conda --binstaruser %BINSTAR_USER% --binstarkey %BINSTAR_KEY%
