build: false

environment:
  global:
    BINSTAR_USER: menpo
    BINSTAR_KEY: temp

  matrix:
    - PYTHON_VERSION: 2
    - PYTHON_VERSION: 3

platform:
- x86
- x64

init:
- ps: Start-FileDownload 'https://raw.githubusercontent.com/jabooth/condaci/master/condaci.py' .\\condaci.py; echo Done
- python condaci.py setup %PYTHON_VERSION% --binstarchannel %BINSTAR_USER%

install:
- C:\\Miniconda\\python condaci.py auto conda --binstaruser %BINSTAR_USER% --binstarkey %BINSTAR_KEY%
