build: false

environment:
  global:
    BINSTAR_USER: menpo
    BINSTAR_KEY: temp
  matrix:
    - PYTHON_VERSION: 2
    - PYTHON_VERSION: 3

platform:
- x64

init:
- ps: Start-FileDownload 'https://raw.githubusercontent.com/jabooth/traviconda/master/traviconda.py' C:\\traviconda.py; echo "Done"
- python C:\\traviconda.py setup %PYTHON_VERSION% --channel %BINSTAR_USER%

install:
- C:\\Miniconda\\python C:\\traviconda.py auto ./conda --binstarchannel main --binstaruser %BINSTAR_USER% --binstarkey %BINSTAR_KEY%
